name: Deploy to Dev

on:
  push:
    branches-ignore:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Lint code with flake8
        run: |
          flake8 src/  

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python
      
      - name: Run tests with pytest
        run: |
          pytest tests/


